#:kivy 2.0.0

BoxLayout:
    orientation: "vertical"
    padding: 10
    spacing: 10

    BoxLayout:
        size_hint_y: 0.2
        Label:
            id: status_text
            text: "Status: Ready"
    BoxLayout:
        id: names_box
        size_hint_y: 0.7
        Label:
            text: "Main content goes here"
    # Added label per prac instruction, taking ~10% height
    Label:
        text: "I did this :)"
        size_hint_y: 0.1
